Repository leapfrogtechnology/sync-db, pull requests merged in 2019-11, with the labels that each got.

#24 Use knex to create, run, rollback migrations with samples
  examples/node-app-mssql/.babelrc
  examples/node-app-mssql/.eslintrc
  examples/node-app-mssql/README.md
  examples/node-app-mssql/knexfile.js
  examples/node-app-mssql/package.json
  examples/node-app-mssql/src/migrations/20191124213750_create_user_table.js
  examples/node-app-mssql/src/migrations/20191124213800_create_task_table.js
  examples/node-app-mssql/yarn.lock
Labels: documentation, example

#27 Upgrade TypeScript to 3.7.2
  package.json
  yarn.lock
Labels: dependencies

#26 Upgrade knex minimum version to 0.19.5
  examples/node-app-mssql/package.json
  examples/node-app-mssql/yarn.lock
  package.json
  yarn.lock
Labels: dependencies, security

#28 Throw an error if object type names doesn't match directory convention
  src/sqlRunner.ts
  test/sqlRunner.test.ts
Labels: bugfix

#29 Added an example showing programmatic usuage of sync-db Node/JS
  README.md
  examples/node-mssql-programmatic-use/.babelrc
  examples/node-mssql-programmatic-use/.eslintrc
  examples/node-mssql-programmatic-use/.gitignore
  examples/node-mssql-programmatic-use/Dockerfile
  examples/node-mssql-programmatic-use/README.md
  examples/node-mssql-programmatic-use/connections.sync-db.json.docker
  examples/node-mssql-programmatic-use/connections.sync-db.json.example
  examples/node-mssql-programmatic-use/docker-compose.yml
  examples/node-mssql-programmatic-use/knexfile.js
  examples/node-mssql-programmatic-use/package.json
  examples/node-mssql-programmatic-use/src/index.js
  examples/node-mssql-programmatic-use/src/migrations/20191124213750_create_user_table.js
  examples/node-mssql-programmatic-use/src/migrations/20191124213800_create_task_table.js
  examples/node-mssql-programmatic-use/src/sql/function/dbo/square.sql
  examples/node-mssql-programmatic-use/src/sql/function/dbo/sum.sql
  examples/node-mssql-programmatic-use/src/sql/function/utils/product.sql
  examples/node-mssql-programmatic-use/src/sql/procedure/utils/get_date.sql
  examples/node-mssql-programmatic-use/src/sql/schema/utils.sql
  examples/node-mssql-programmatic-use/src/sql/view/utils/vw_table_names.sql
  examples/node-mssql-programmatic-use/src/sql/view/utils/vw_user_names.sql
  examples/node-mssql-programmatic-use/src/sync-db.js
  examples/node-mssql-programmatic-use/sync-db.yml
  examples/node-mssql-programmatic-use/yarn.lock
Labels: example, programmatic-api
