Repository leapfrogtechnology/sync-db, pull requests merged in 2019-08, with the labels that each got.

#4 Set published source for sync-db
  README.md
  examples/node-app-mssql/README.md
  examples/node-app-mssql/package.json
  examples/node-app-mssql/src/index.js
  examples/node-app-mssql/yarn.lock
Labels: documentation

#7 Improvements on the README Documentation
  README.md
Labels: documentation

#10 Enable passing connection instance as well as connection config for synchronization
  README.md
  package.json
  src/Connection.ts
  src/config.ts
  src/constants.ts
  src/domain/Connection.ts
  src/domain/ConnectionConfig.ts
  src/domain/DbConfig.ts
  src/domain/RawBingingParams.ts
  src/domain/SyncConfig.ts
  src/logger.ts
  src/migrator.ts
  src/sqlRunner.ts
  src/util/db.ts
Labels: documentation, enhancement, feature

#11 Simplify programmatic usage and documentation
  README.md
  bin/run
  docs/.gitkeep
  docs/sql.md
  src/index.ts
  test/index.test.ts
Labels: cli, documentation, programmatic-api

#13 Configure Travis CI for running tests
  .travis.yml
  README.md
Labels: test

#15 Support knex transactions in synchronize
  src/Connection.ts
  src/domain/DbConnectionInstance.ts
  src/migrator.ts
Labels: enhancement

#16 Downgrade knex version to 0.16.3
  package.json
  src/Connection.ts
  src/domain/DbConnectionInstance.ts
  src/migrator.ts
  yarn.lock
Labels: dependencies
