Repository leapfrogtechnology/sync-db, pull requests merged in 2020-03, with the labels that each got.

#45 Support resolving connections from the environment directly as a fallback option
  src/config.ts
  src/constants.ts
  test/config.test.ts
Labels: feature

#46 Fix fs.exists() util ¯\_(ツ)_/¯
  src/util/fs.ts
  test/fs.test.ts
Labels: bug, test, util

#47 Fix ramda merge convert issue ¯\(ツ)/¯
  src/api.ts
Labels: bug, bugfix

#48 Bump knex version to 0.20.11
  package.json
  yarn.lock
Labels: chore, dependencies

#50 Support resolution of local project dependencies when CLI is invoked in development mode
  README.md
  bin/run-dev.sh
  package.json
Labels: cli, dev efficiency

#56 Setup prettier and integrate format checking in the CI
  .nycrc.json
  .prettierignore
  .travis.yml
  examples/node-app-pg/src/index.js
  examples/node-mssql-programmatic-use/src/index.js
  package.json
  src/domain/ConnectionConfig.ts
  src/domain/RawBingingParams.ts
  test/env.test.ts
  test/tsconfig.json
  tslint.json
  yarn.lock
Labels: aesthetics

#55 Support both sequential and parallel execution strategies for running synchronization
  examples/node-app-mssql/sync-db.yml
  src/SyncDb.ts
  src/api.ts
  src/constants.ts
  src/domain/SyncConfig.ts
  src/services/execution.ts
  src/services/sqlRunner.ts
  src/services/sync.ts
  src/util/promise.ts
  src/util/ts.ts
  test/promise.test.ts
  test/service/execution.test.ts
Labels: config, feature, internals

#57 Organize directories and minor improvements for consistency and trivial fixes
  bin/run
  bin/run-dev.sh
  src/SyncDb.ts
  src/api.ts
  src/config.ts
  src/domain/SyncContext.ts
  src/enum/DatabaseObjectTypes.ts
  src/service/configInjection.ts
  src/service/execution.ts
  src/service/sqlRunner.ts
  src/service/sync.ts
  test/service/configInjection.test.ts
  test/service/execution.test.ts
  test/service/sqlRunner.test.ts
  test/util/config.test.ts
  test/util/env.test.ts
  test/util/fs.test.ts
  test/util/promise.test.ts
  test/util/types.test.ts
Labels: aesthetics, chore, improvement

#60 Drop Node 8.x support - minimum required version >= 10.x
  .travis.yml
  package.json
Labels: breaking change, chore, dependencies

#61 Upgrade prettier and reformat code
  .prettierrc
  examples/node-app-mssql/.eslintrc
  examples/node-app-mssql/docker-compose.yml
  examples/node-app-mssql/src/migrations/20191124213800_create_tasks_table.js
  examples/node-app-pg/docker-compose.yml
  examples/node-app-pg/src/migrations/20191202053206_todos.js
  examples/node-mssql-programmatic-use/.eslintrc
  examples/node-mssql-programmatic-use/docker-compose.yml
  examples/node-mssql-programmatic-use/src/migrations/20191124213800_create_task_table.js
  package.json
  yarn.lock
Labels: aesthetics, dependencies
